---

all:
  vars:
    remote_user: aborgardt
    become: yes
    become_method: sudo
    ansible_sudo_pass: 'Kra05n+='
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
    pc944-virt:
      ansible_host: 10.25.0.70
      
      