---

all:
  vars:
    remote_user: aborgardt
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
    pc944-virt:
      ansible_host: 10.25.0.70
      become: yes
      become_method: sudo
      
      